sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    # - DB=mysql
    - GLPI_SOURCE="https://github.com/glpi-project/glpi"
    - CS=7.2
    - DBNAME=glpitest
    - OLDDBNAME=glpiupgradetest
    - AFTER_SUCCESS_BRANCH=9.3/bugfixes
  matrix:
#    - GLPI_BRANCH=9.1/bugfixes
    - GLPI_BRANCH=9.2/bugfixes
    - GLPI_BRANCH=9.3/bugfixes
    - GLPI_BRANCH=master

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - "./tests/before_script.sh"
#  # Update composer
#  - composer self-update
#  # Dump Mysql version
#  - mysql -u root -e 'select version();'
#  # Get and prepare Glpi application
#  - cd ..
#  - git clone --depth=1 https://github.com/glpi-project/glpi glpi -b $GLPI
#  - cd glpi
#  - pwd
#  - composer install --no-dev
#  - mysql -u root -e 'create database glpi_test;'
#  # Prepare test database
#  - php ./scripts/cliinstall.php --db=glpitest --user=root --tests
#  - php ./scripts/cliupdate.php --config-dir=../tests |grep -q "No migration needed." || (echo "scripts/cliupdate.php FAILED" && exit 1)
#  # Install alignak plugin in Glpi
#  - mv ../glpi_alignak plugins/alignak
#  - cd plugins/alignak
#  - composer install -o

script:
  # Plugin unit tests
  - if [ "${TRAVIS_PHP_VERSION:0:3}" = "$CS" ] && [ "$GLPI_BRANCH" = "$AFTER_SUCCESS_BRANCH" ]; then COVERAGE="--nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI"; else COVERAGE="-ncc"; fi
  - if [ -e ../../scripts/cliinstall.php ] ; then php ../../scripts/cliinstall.php --db=$OLDDBNAME --user=root --tests ; fi
  - if [ -e ../../tools/cliinstall.php ] ; then php  ../../tools/cliinstall.php --db=$OLDDBNAME --user=root --tests ; fi
  - mysql -u root $OLDDBNAME < tests/plugin_alignak_empty_1.0.0.sql
  - mysql -u root $OLDDBNAME < tests/plugin_alignak_config_1.0.0.sql
  - php scripts/cliinstall.php --tests
  - rm ../../tests/config_db.php
  - if [ -e ../../scripts/cliinstall.php ] ; then php ../../scripts/cliinstall.php --db=$DBNAME --user=root --tests ; fi
  - if [ -e ../../tools/cliinstall.php ] ; then php ../../tools/cliinstall.php --db=$DBNAME --user=root --tests ; fi
  - vendor/bin/atoum --debug -ft -bf tests/bootstrap.php -d tests/ts-install -ncc
#  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-integration $COVERAGE
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/ts-unit $COVERAGE
  #  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-uninstall -ncc

  # PHP coding standards
  #  - ./vendor/bin/robo --no-interaction code:cs
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ] && [ "$GLPI_BRANCH" = "$AFTER_SUCCESS_BRANCH" ]; then vendor/bin/robo --no-interaction code:cs; fi
  #  - ./vendor/bin/atoum ++verbose --debug -bf tests/bootstrap.php -d tests/ts-unit

matrix:
#  exclude:
#    - php: 5.4
#      env: GLPIVER=master
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#channel"
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true
